/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinica;

import javax.swing.SwingUtilities;

/**
 *
 * @author victo
 */
public class VentanaProductos extends javax.swing.JFrame {
    
    private AsignarProductos asignacion;

    /**
     * Creates new form VentanaProductos
     */
    
    VisualizarTablas visualizarTab= new VisualizarTablas();
    DiseñoTablas tablas = new DiseñoTablas();
    
    public VentanaProductos(AsignarProductos asignacion) {
        this.asignacion = asignacion;
        initComponents();
        tablas.personalizarTabla(jTable5);
        tablas.personalizarRenderizado(jTable5);
        verTablaProductosTratamientos();
    }

    public VentanaProductos() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        jLabel1.setText("Productos");

        jTable5.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Producto", "Producto", "Descripcion", "Precio Unitario", "Cantidad Disponible"
            }
        ));
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = jTable5.getSelectedRow();
        if (filaSeleccionada != -1) {
            String nombre = jTable5.getValueAt(filaSeleccionada, 1).toString();
            int id = Integer.parseInt(jTable5.getValueAt(filaSeleccionada, 0).toString());

            if (asignacion == null || !asignacion.isDisplayable()) {
                asignacion = new AsignarProductos();
            }
            asignacion.setVisible(true);
            SwingUtilities.invokeLater(() -> {
                asignacion.abrirVentanaProducto(id, nombre);
            });
        }
    }//GEN-LAST:event_jTable5MouseClicked

    private void verTablaProductosTratamientos() {
        String sql = "SELECT DISTINCT p.idProducto, " +
                     "p.NombreProducto, p.Descripcion, p.PrecioUnitario, " +
                     "pp.CantidadDisponible " +
                     "FROM Productos p " +
                     "INNER JOIN ProveedorProducto pp ON p.idProducto = pp.idProducto ";
        
        String[] columnas = {"idProducto", "NombreProducto", "Descripcion", "PrecioUnitario", "CantidadDisponible"};
        visualizarTab.cargarDatos(jTable5, sql, columnas);
    }
   
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable5;
    // End of variables declaration//GEN-END:variables
}
